### ISSUE TITLE
Redirections cause builtins to have no effect

### ISSUE THREAD

**Issue by jmi2k** [rakitzis/rc#62] opened 2020-08-28 23:46 UTC
For example, try doing:

```rc
; cd /some/path/somewhere > /dev/null
; pwd
/your/pwd
```

Presumably generalizable to other commands (I just don't know how to test this with another command/builtin)

**Comment by rakitzis** [comment] 2020-08-30 00:27
Builtins will execute in a subshell if redirection is used, so that explains the behavior.

**Comment by jmi2k** [comment] 2020-08-30 00:50
Is it expected behavior? I hope it isn't, it's really confusing...

**Comment by rakitzis** [comment] 2020-08-30 01:25
Well, "expected" in the sense that it's worked this way for 30 years. You may be the first to raise it as a problem! I fear that it would take a significant restructure to change this behavior.

**Comment by jmi2k** [comment] 2020-08-30 01:38
I understand, in fact me having this problem was caused by me trying to (improperly) handle a cd to nowhere. I've spun up my Plan 9 VM and at least it seems to work correctly there, so it's a quirk of this implementation.
I fully understand that the solution can be difficult for very little to no gain, so what do you want me to do with this issue? Leaving it open as some kind of documentation (just in case there is a second "me" out there trying to do things wrong), or closing it?

![image](https://user-images.githubusercontent.com/17623703/91649236-1f44df00-ea72-11ea-9a57-6aed2330e4ad.png)

**Comment by rakitzis** [comment] 2020-08-30 01:49
Well, I'm not in charge of maintaining rc these days! But I'd say leave it open. It does seem like a hair-splitting issue, as you say, one with little gain. More importantly, I'd be concerned that any fix didn't regress the shell in other, more important ways.

**Comment by xyb3rt** [comment] 2023-06-12 10:16
This even effects `break`, `continue` and `return` because they're implemented as builtins!

**Comment by rakitzis** [comment] 2023-06-12 13:32
Yes, this explains the other issue on return with a redirection. Do you have an idea of how plan9 rc saves and restores fd state for builtin redirections? I haven't examined the source.

As I said earlier the fix is probably not a point fix, as the strategy rc uses for applying redirections to do it after `fork()` and before `exec()`. The kernel gives the subprocess a copy-on-write duplicate of the fd state, while the parent's fd state is never altered.

This strategy does not work for builtins, since they neither `fork()` nor `exec()`. The exception here is applying redirections on the `exec` builtin: you get exactly the effect you want (as in the Bourne shell) of altering the fd set of the controlling shell.

**Comment by xyb3rt** [comment] 2023-06-13 08:11
I think we should either overhaul this completely, which might break existing scripts or not do it at all. The proper way would be to set up redirections like variables and push a frame onto estack so that we can reverse them.

Limiting temporary redirections to simple commands calling a builtin would not solve these cases that bash also does not handle in a subshell:
```
foo() {
    cd "$@"
    pwd
}
foo / >/dev/null
```
```
for f in *; do cd /; echo "$f"; done >/dev/null
```
Both output nothing and end up in `/`.
```

**Comment by rakitzis** [comment] 2023-06-13 15:00
I agree. I ended up in the same place, by leaving this behavior alone. I'm not sure if it's worth a fix, even though it breaks the principle of "least surprise".

**Comment by rakitzis** [comment] 2024-08-25 21:50
Without a solid proposal for a fix, or without a view as to what this would break (as it's a breaking change) I will mark this closed for now.

**Closed by rakitzis** 2024-08-25 21:50 UTC
